    /* i hate putting include-once data into .h, but this seems sadly\n"
    "   like it's the most appropriate thing to do here.\n"
    "*/

static char conf_txt[1500] = 
    "# configuration file for model-t-shell\n"
    "#\n"
    "#  2012-11 Scott Lawrence  yorgle@gmail.com\n"
    "#\n"
    "# The format of these items is basically:\n"
    "#	Category.Key = Value   # comment\n"
    "# 	Category.Key = @keyReference \n"
    "# 	Category.Key = %InternalCommand\n"
    "#\n"
    "#	Category.Key=Value\n"
    "#	Category.Key=Value #.*\n"
    "\n"
    "# general system configurations\n"
    "System.TopBarLeft=@DATE\n"
    "System.TopBarRight=@USER - @VERSION\n"
    "System.ConfVersion=1.0\n"
    "System.ConfFile=/home/sdl/.modeltsh/conf.txt\n"
    "System.SkipDotFiles=1\n"
    "\n"
    "# list of all places that show up in the listing\n"
    "Places.Parent=.. (Parent)	# display, not actual path on this one\n"
    "Places.Home= 		#(on first run, replaced with $HOME)\n"
    "Places.Cwd= 		#(on first run, replaced with CWD)\n"
    "Places.Root=/\n"
    "\n"
    "# Verbs are executables that can be run with 0 or 1 parameter\n"
    "Verbs.PICO=/usr/bin/pico\n"
    "Verbs.VI=/usr/bin/vi\n"
    "Verbs.MORE=/bin/more\n"
    "Verbs.SHELL=/bin/sh\n"
    "Verbs.ADD=%ADD		# add the directory to places, exe to verbs, save config\n"
    "Verbs.REMOVE=%REMOVE	# remove the selected item, save config\n"
    "Verbs.RELOAD=%RELOAD	# reloads this file\n"
    "Verbs.EXIT=%EXIT	# exits from the interface\n"
    "\n"
    "# VerbAliases are additional verbs, but their target\n"
    "# is an actual Verb or alias\n"
    "VerbAlias.EDIT=@Verbs.PICO\n"
    "VerbAlias.RUN=@Verbs.SHELL\n"
    "\n"
    "# File verbs associate file extensions with Verbs and Verb Aliases\n"
    "File.h=EDIT\n"
    "File.c=EDIT\n"
    "File.txt=EDIT\n"
    "File.md=EDIT\n"
    "File.cc=EDIT\n"
    "File.doc=EDIT\n"
    "File.do=EDIT\n"
    "File.bas=EDIT\n"
    "File.ba=EDIT\n"
    "File.sh=RUN\n"
    "File.bat=RUN\n"
    "File.exe=RUN\n";
